apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: app-config
data:
  appsettings.json: |-
    {
      "Database": {
        "ConnectionString": "Sample connection string"
      }
    }