# source code: https://stackoverflow.com/questions/63217356/sql-server-pods-with-persistentvolumeclaim
# sqlserver.yaml
apiVersion: v1
kind: Pod
metadata: 
  name: sqlserver
spec:
  initContainers:
  - name: volume-permissions
    image: busybox
    command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
    volumeMounts:
    - mountPath: "/var/opt/mssql"
      name: sqldata-storage
  volumes:
  - name: sqldata-storage
    persistentVolumeClaim:
      claimName: dbclaim
  containers:
  - image: mcr.microsoft.com/mssql/server
    name: foo
    volumeMounts:
    - mountPath: "/var/opt/mssql/data"
      name: sqldata-storage
    env:
    - name: ACCEPT_EULA
      value: "Y"
    - name: SA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mssql
          key: SA_PASSWORD
    - name: MSSQL_PID
      value: Developer

---

#pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqldata-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/sqldata"
  
---

#pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: mssql
type: Opaque
data:
  SA_PASSWORD: UzBtZXRoaW5nU0BTdHIwbmch

