apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-deployment
  labels:
    app: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      volumes: 
        - name: file-share-volume
          persistentVolumeClaim:
            claimName: file-share-volume-claim
        - name: app-config-volume
          configMap:
            name: app-config
        - name: secrets
          secret:
            secretName: secret-appsettings
      containers:
      - name: api-deployment-pod
        image: samplewebapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts: 
          - name: file-share-volume
            mountPath: /home/files
          - name: app-config-volume
            mountPath: /app/config
          - name: secrets
            mountPath: /app/sensitive-config
            readOnly: true
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "200m" #200 millicpu (.2 cpu or 20% of the cpu)
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2 # Default is 1
          periodSeconds: 5 # Default is 10
          failureThreshold: 1 # Default is 3
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5 # Default is 10
          failureThreshold: 1 # Default is 3
