apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-processor-deploy
  labels:
    app: file-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-processor
  template:
    metadata:
      labels:
        app: file-processor
    spec: 
      terminationGracePeriodSeconds: 1
      volumes: 
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: file-processor-pod
        image: pcarcere/fileprocessor:latest
        env:
          - name: INPUT_FOLDER
            value: "./files"
        imagePullPolicy: Always
        # processor is ready when the file generator has generated some file in /app/files folder
        readinessProbe:
          exec:
            command:
            - find 
            - /app/files
          initialDelaySeconds: 5 
          periodSeconds: 5
        volumeMounts: 
        - name: task-pv-storage
          mountPath: /app/files
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"