apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-processor-deploy
  labels:
    app: file-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-processor
  template:
    metadata:
      labels:
        app: file-processor
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: file-generator-pod
        image: pcarcere/filegenerator:latest
        imagePullPolicy: Always
      - name: file-parser-pod
        image: pcarcere/fileparser:latest
        imagePullPolicy: Always