apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-processor-deploy
  labels:
    app: file-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-processor
  template:
    metadata:
      labels:
        app: file-processor
    spec: 
      terminationGracePeriodSeconds: 1
      volumes: 
      - name: files 
        emptyDir: {} 
      containers:
      - name: file-generator-pod
        image: pcarcere/filegenerator:latest
        imagePullPolicy: Always
        volumeMounts: 
        - name: files 
          mountPath: /app/files
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: file-parser-pod
        image: pcarcere/fileparser:latest
        imagePullPolicy: Always
        volumeMounts: 
        - name: files 
          mountPath: /app/files
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"