apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-share-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/files"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-share-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi